### ISSUE TITLE
Enable/disable wifi

### ISSUE THREAD

**Issue by azizbekian** [ashishb/adb-enhanced#109]
It would be handy to have a possibility for enabling/disabling wifi using adbe.

With standard adb it could be done using following commands:

```
adb shell svc wifi disable
adb shell svc wifi enable
```

**Comment by ashishb** [comment]
Are you sure it works? I think last I checked it was only working for older devices

**Comment by azizbekian** [comment]
I can confirm, that it works on latest Pixel emulator builds (running Android 10). Haven't tested on an actual device though.

**Comment by ashishb** [comment]
It will be in the next release. I am thinking of doing it sometime the end of this week.
