### ISSUE TITLE
[Feature request] When multiple devices connected issue command to all of them

### ISSUE THREAD

**Issue by YuraLaguta** [ashishb/adb-enhanced#11]
When using adbe and have multiple devices connected an error is thrown,
Would it be appropriate to just send the command to all devices?
here is some small shell script in accepted answer: https://stackoverflow.com/questions/17882474/running-adb-commands-on-all-connected-devices

**Comment by YuraLaguta** [comment]
Few options come to mind:
Param -a to execute on all devices, ignore output, for example when I'm uninstalling I just want to make sure it's uninstalled. 
Screenshot and pulling might not support this option, unless there is a strong usecase for it

**Comment by ashishb** [comment]
That makes sense, so, rather than being a blanket option, this could be enabled only for very specific options. Which options do you think this could be useful for? The uninstall example you provided does not apply to adbe since as of now, it does not have uninstall sub-command.

**Comment by ashishb** [comment]
I don't think this makes sense in most of the cases. I will close it for now, I can reconsider it at a later point if there is good enough argument to do it.

**Comment by YuraLaguta** [comment]
Animations on/off is what triggered me to write this issue

**Comment by YuraLaguta** [comment]
Animations is what triggered me to write this issue
