### ISSUE TITLE
install  fail， No such file or directory: 'version.txt'

### ISSUE THREAD

**Issue by AU3904** [ashishb/adb-enhanced#12]
hello ，ashishb, it is fail when i install this tools,   help

➜  ~ sudo pip install adb-enhanced
The directory '/Users/lu/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/lu/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting adb-enhanced
  Downloading https://files.pythonhosted.org/packages/e9/58/b0f54dd63d4ee28e3fbb656ff76bc6c5be60d3591837214704d604a0cf04/adb-enhanced-1.8.8.tar.gz (338kB)
    100% |████████████████████████████████| 348kB 502kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-CWbKNB/adb-enhanced/setup.py", line 4, in <module>
        with open('version.txt', 'r') as fh:
    IOError: [Errno 2] No such file or directory: 'version.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-CWbKNB/adb-enhanced/
➜  ~
➜  ~

**Comment by ashishb** [comment]
Wow. I am able to reproduce this but I am not sure why has this started now. Let me disable this, make the code workable and fix it later.

**Comment by ashishb** [comment]
In the meanwhile, you can install via python3 `pip3 install adb-enhanced`

**Comment by ashishb** [comment]
Culprit diff: https://github.com/ashishb/adb-enhanced/commit/b2b56200c28b2ab86734dec5e2ee79a9b261a952

**Comment by ashishb** [comment]
The entries were missing in MANIFEST.in - I fixed it in https://github.com/ashishb/adb-enhanced/commit/e2320a1a7856fb55d58411566b63a3ceccfe154d

**Comment by ashishb** [comment]
Fixed in 1.8.16
