### ISSUE TITLE
Support Alarm Manager output.

### ISSUE THREAD

**Issue by nguyencongbinh** [ashishb/adb-enhanced#120]
I can check all alarms of my app with this script
**adb shell dumpsys alarm | grep -A 2 com.myapp.name**

The output is useful but show a lot of information and is hard to read. It will be great if you can take time to work on this. Thank you.

**Comment by ashishb** [comment]
Thanks for filing the issue. I have not played much with alarms before, can you post the output of 
`adb shell dumpsys alarm | grep -A 2 com.myapp.name`?

**Comment by SecTheTech** [comment]
That can be a good feature, I'll send a pull request for this issue.

**Comment by ashishb** [comment]
Assigned to you, @SecTheTech. Thanks.

**Comment by SecTheTech** [comment]
Added on the pull request #131.
