### ISSUE TITLE
adbe shell not working

### ISSUE THREAD

**Issue by saurabhlucideus** [ashishb/adb-enhanced#124]
How can we use **adbe shell** as similar to **adb shell** command and getting the shell access of the device.

**Comment by ashishb** [comment]
@saurabhlucideus `adbe shell` does not exist because `adb shell` works. And you need `adb` for `adbe` anyways. I didn't want to duplicate the functionality of `adb` as-is. I am curious why do you want `adbe shell`?

**Comment by saurabhlucideus** [comment]
I thought the adb was completely enhanced to adbe and all the commands will be working in that manner.

**Comment by ashishb** [comment]
Thanks. I added a clarification - https://github.com/ashishb/adb-enhanced/commit/1436e207b6f72ee43ec8d459aa6863db55773a54#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by saurabhlucideus** [comment]
Thank you for the clarification
