### ISSUE TITLE
Add Notification Support

### ISSUE THREAD

**Issue by MS-Jahan** [ashishb/adb-enhanced#129]
Please add support for gathering notification.

**Comment by ashishb** [comment]
Can you elaborate on what kind of notification access are you looking at?

**Comment by MS-Jahan** [comment]
We can normally get on-screen notification info and other stuff using this command: `adb shell sysdump notification`

It would be great to have some thing like `adbe get notifications` and then output like:
```
<App name>:
    Title: <title>
    Subtitle: <subtitle>
    Buttons: <buttons>
```

**Comment by ashishb** [comment]
Added in d291ec71e43ebfc6ca6af155db819f30c5b3c8b8

**Comment by MS-Jahan** [comment]
Thank you so much
