### ISSUE TITLE
Cannot install using pip3

### ISSUE THREAD

**Issue by IgorGanapolsky** [ashishb/adb-enhanced#14]
Hello,
I run this command:
`sudo pip3 install adb-enhanced`
and get this error:
> Collecting adb-enhanced
  Could not fetch URL https://pypi.python.org/simple/adb-enhanced/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement adb-enhanced (from versions: )
No matching distribution found for adb-enhance

Any ideas?

**Comment by ashishb** [comment]
This seems like a temporary issue with Python.org's certificate being rejected. Food retrying it fixes it?

**Comment by IgorGanapolsky** [comment]
Still error occurs...

**Comment by ashishb** [comment]
As per https://github.com/pypa/pip/issues/5236, you need to upgrade pip using `curl https://bootstrap.pypa.io/get-pip.py | python3`

**Comment by IgorGanapolsky** [comment]
That produces an error: "AttributeError: module 'lib' has no attribute
'SSL_ST_INIT'"

**Comment by ashishb** [comment]
I am out of fixes here. Something is broken with your python installation and I don't think you can install any python packages till you fix that.
