### ISSUE TITLE
Add support for enabling show touches 

### ISSUE THREAD

**Issue by arranlomas** [ashishb/adb-enhanced#15]
As the title suggests, there is an option in developer options (see screenshot below, take from samsung) to show touches, this is great for screen records. would be nice to have something like `adbe touches on/off`. Thanks for the awesome tool!

![screen shot 2018-10-02 at 12 12 17 pm](https://user-images.githubusercontent.com/22332838/46325616-7a7ab680-c63c-11e8-8932-b1d92243eeac.png)

**Comment by ashishb** [comment]
Implement `show-taps` in https://github.com/ashishb/adb-enhanced/commit/37cad121d60e8ecf1879b237a59efe4ad93fef6f

**Comment by ashishb** [comment]
This is part of the 1.9.5 version release.
