### ISSUE TITLE
Possible fix for set_dark_mode

### ISSUE THREAD

**Issue by yschimke** [ashishb/adb-enhanced#161]
I noticed

https://github.com/ashishb/adb-enhanced/blob/d704cce0d98dbea9dcb65981d84c10a4ac572c49/adbe/adb_enhanced.py#L1825-L1840

I wonder if this is the fix?

https://twitter.com/petedoyle_/status/1502008461080490006

![image](https://user-images.githubusercontent.com/231923/157821437-6137b96c-fef4-4ae9-890e-c7efff4a9c62.png)

**Comment by ashishb** [comment]
This looks great. Would you like to send a fix? If not, I can make the change as well.

**Comment by yschimke** [comment]
Sure.  I'll need to test it first.  I was just flagging this currently.

**Comment by ashishb** [comment]
Sent https://github.com/ashishb/adb-enhanced/pull/162
