### ISSUE TITLE
ADBE screenshot to clipboard

### ISSUE THREAD

**Issue by maarten2000ha** [ashishb/adb-enhanced#216]
I use want to use this tool with testing and don't want to clog my drive full of screenshot and recordings. Is there a possibility to copy it to clipboard instead of only to a file?

suggestions: 
`adbe screenshot | pbclip`(mac but can also maybe pipe into xclip) or  `abde screenshot clip`

**Comment by ashishb** [comment]
Thanks @maarten2000ha for the suggestion.
Why not `adbe screenshot /tmp/tmp1.png && <copy to keyboard in Mac/Linux dependent way> && rm /tmp/tmp1.png`?
