### ISSUE TITLE
Default screenshot filename

### ISSUE THREAD

**Issue by atanana** [ashishb/adb-enhanced#217]
It seems that it would be convenient to use e.g. timestamp as a filename if no filename is given

**Comment by ashishb** [comment]
Why not use?

```
$ adbe screenshot screenshot-`date +"%Y-%m-%dT%H:%M:%S%z".png`
```

**Comment by atanana** [comment]
yes, of course I can use something like that. But I thought that the main goal of your tool is to make things more simple :) I think it's a quite common use case when you need to take few screenshots, and it's easier to run the same simple command multiple times than type unique screenshot name or google how to use `date` command

**Comment by ashishb** [comment]
Thanks, @atanana for the feedback.
I will consider adding it in the future release.
