### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [ashishb/adb-enhanced#36]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by ashishb** [comment]
Sure, please go ahead.

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![adb enhanced](https://user-images.githubusercontent.com/33461607/48315622-2b487e00-e60b-11e8-871c-0427f26e8c9c.png)
maybe the purpose of the Swiss-army knife is this application is a multifunctional application. but on this logo I use a battery icon with an internet data icon in the middle of the battery icon to explain that this application can save battery but save internet data. and with interrupted circles describing this application can control internet data and batteries.

**Comment by ashishb** [comment]
Thanks. This looks interesting but how about improving this or creating a new logo which implies the following: Android, developer, Swiss army knife.

**Comment by anilkilic** [comment]
Here is an alternative proposal, *Android & Swiss Army Knife*;

![image](https://user-images.githubusercontent.com/2311397/48378607-4803b500-e6e2-11e8-8763-9b5a9fff18a7.png)

**Comment by mansya** [comment]
what about the logo that I have changed? will this be like a swiss army knife?
![adb enhanced](https://user-images.githubusercontent.com/33461607/48468411-5656eb80-e81e-11e8-96bc-1dd4b866b556.png)

**Comment by anilkilic** [comment]
Here you can find svg and png files of different versions like logomark only or with logotype or only black-white, let me know if you need any other alternatives. I saw you also going to prepare a readthedocs file so I didn't make a pull request to keep it clean. 
[google:drive](https://drive.google.com/open?id=1isjKPbRSA59G8YRTmeeT_LKGqeSOsm7k)

**Comment by ashishb** [comment]
@mansya Small suggestion how about replace the knife in swiss-army knife with an Android figurine. Something like https://phandroid.s3.amazonaws.com/wp-content/uploads/2014/02/mega-android-collectible-2.jpg

**Comment by mansya** [comment]
this will be interesting. I like your suggestion. and I will do it. please wait.

**Comment by mansya** [comment]
did you mean like this ?
![adb enhanced](https://user-images.githubusercontent.com/33461607/48564916-e6ce2280-e929-11e8-9c32-46d1cf2ad118.png)

**Comment by ashishb** [comment]
Top one looks great.

**Comment by ashishb** [comment]
Thanks @mansya

**Comment by mansya** [comment]
I want to make pull requests for this project. because I need that. and after that I will give all vector files about this logo. please wait.

**Comment by ashishb** [comment]
Sure

**Comment by mansya** [comment]
I have uploaded all of the files to this [**drive**](https://drive.google.com/open?id=18Ot2X9FcgN67pc4faV1IKLKW_Oqh9SWY). and I have sent you [**Pull Requests**](https://github.com/ashishb/adb-enhanced/pull/42). please check

**Comment by ashishb** [comment]
Thanks. The new logo can be seen at https://github.com/ashishb/adb-enhanced

Ashish
