### ISSUE TITLE
Top-Activity improvement

### ISSUE THREAD

**Issue by ivopnv** [ashishb/adb-enhanced#4]
Hey man great work!

I've noticed that the top-activity command only shows the package name, ex:

`* Recent #0: TaskRecord{85f2327 #15 A=com.google.android.apps.photos U=0 StackId=1 sz=1}\n`

I use something better like:

`adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp`

that will output:

`mCurrentFocus=Window{e615992 u0 com.google.android.apps.photos/com.google.android.apps.photos.home.HomeActivity}
  mFocusedApp=AppWindowToken{1c2affb token=Token{fdee9da ActivityRecord{a9f0785 u0 com.google.android.apps.photos/.home.HomeActivity t15}}}`

Here we can clearly see that the activity name `HomeActivity`. Feel free to use it or modify the command as you wish 👍

**Comment by ashishb** [comment]
This is definitely more useful. Thanks for raising this, would you like to make the change?

**Comment by ashishb** [comment]
I made the change in https://github.com/ashishb/adb-enhanced/commit/5f803261cb5319278945763c5dfd8d18d335f710
