### ISSUE TITLE
facing issue while running the command

### ISSUE THREAD

**Issue by nischaysingla** [ashishb/adb-enhanced#5]
./adbe: No such file or directory

**Comment by ashishb** [comment]
Did you try "sudo pip install adb-enhanced"? Calling this without sudo
doesn't put the binary in the bin directory for me.

**Comment by kaciula** [comment]
I think the issue is that you are running the command in your current directory ( ./adbe ). You should run the command without the "./" prefix.

**Comment by ashishb** [comment]
I added "sudo" to the installation step. Marking this as closed.
