### ISSUE TITLE
Android Studio plugin wrapping this tool

### ISSUE THREAD

**Issue by kaciula** [ashishb/adb-enhanced#6]
It would be great if there was an Android Studio plugin that wrapped the functionality of this tool. 

I use a plugin called ADB Idea for adb commands. However, it has much less functionality than this project. Maybe you can talk to the developer for ADB Idea to include this tool inside his plugin somehow.

Just an idea. Great tool! Thanks!

**Comment by ashishb** [comment]
Thanks, great suggestion, I have some other plans in mind but if someone wants to add Android Studio plugin that would be great.
