### ISSUE TITLE
[Feature request] Toggle for animations on/off similar to do not keep activities?

### ISSUE THREAD

**Issue by YuraLaguta** [ashishb/adb-enhanced#7]
It would be great

**Comment by ashishb** [comment]
Sounds good, I will implement using https://stackoverflow.com/a/43861179 in the next version.

**Comment by ashishb** [comment]
Added support to toggle animations in https://github.com/ashishb/adb-enhanced/commit/6373da3fb739c8f69c7df2a08b49f07433b7547c

@YuraLaguta If it does not work on a device, you encounter, please raise another issue.
