### ISSUE TITLE
Consider adding auto-completion for bash and zsh

### ISSUE THREAD

**Issue by ubaierbhat** [ashishb/adb-enhanced#81]
Consider adding completion for bash and zsh.

**Comment by ashishb** [comment]
Thanks for the suggestion. I thought about it earlier. Unfortunately, it seems its a bit involved, especially, for dynamic completions (eg. dir names). I am not prioritizing it right now but I will happily take contributions.

**Comment by ashishb** [comment]
Btw, Note#3 already explains how to set up auto-completion https://github.com/ashishb/adb-enhanced#note

**Comment by ubaierbhat** [comment]
Any idea why it might be failing?
```
Skipping file /usr/share/zsh/5.3/functions/_adbe, no permissions
```

**Comment by ashishb** [comment]
Pretty weird. I will try it out over the weekend and get back to you on this.

**Comment by yschimke** [comment]
Docs suggest this is already there.

> To setup bash/z-sh auto-completion, execute sudo pip3 install infi.docopt-completion && docopt-completion $(which adbe) after installing adb-enhanced.
