### ISSUE TITLE
Add command to have ActivityManager kill a process

### ISSUE THREAD

**Issue by jbarr21** [ashishb/adb-enhanced#82]
Adding this command, which is different than the already existent `force-stop` command, would be very useful in testing cases where the process is killed when [the app is in the background](https://medium.com/inloopx/android-process-kill-and-the-big-implications-for-your-app-1ecbed4921cb) (usually due to something like low memory)

`adb shell am kill <package_name>`

https://stackoverflow.com/a/26890214

**Comment by ashishb** [comment]
Nice idea. How about calling it `adbe safe-kill` or `adb stop --safe-only`? I can definitely implement this but your contributions are welcome as well :)

**Comment by jbarr21** [comment]
I took a look at this, and according the [ActivityManager docs](https://developer.android.com/studio/command-line/adb#am), this only kills app processes in the background that don't affect the user. This leads to the unpredictable success of the command below. I wouldn't want to add a flaky command, so I'm just going to close this out and rely on Android Studio for this.

`adb shell input keyevent KEYCODE_HOME && sleep 3 && adb shell am kill <packageName>`

**Comment by ashishb** [comment]
Thanks. I already have battery level config ability. I wonder if low memory trigger would be valuable as well - https://stackoverflow.com/questions/3656594/simulate-low-battery-low-memory-in-android
