### ISSUE TITLE
Animations toggle on doesn't work

### ISSUE THREAD

**Issue by YuraLaguta** [ashishb/adb-enhanced#9]
Related to #7 
Works fine to toggle off, but doesn't toggling it back on 
Tested on Samsung S8 Android 8 API 26

**Comment by ashishb** [comment]
Fixed in https://github.com/ashishb/adb-enhanced/commit/1c07343f81cf2c62bc8d38a8aa8b7ffd59f48ab3

I tested on API 28. Please test and close if it is fixed for you as well.

**Comment by ashishb** [comment]
It will be part of the next release.

**Comment by YuraLaguta** [comment]
thanks for such a quick fix. Works great!

**Comment by ashishb** [comment]
It's part of 1.7.4 release.
