### ISSUE TITLE
Reporting to use python3 even though it was installed with pip3

### ISSUE THREAD

**Issue by lordcodes** [ashishb/adb-enhanced#94]
I install adb-enhanced with pip3 and have python 3.7 setup on my system.
asyncio is also correctly installed.

However, when I run adbe apps list debug, it prints out "Use python3 for faster execution of this call".

Do you know or have any ideas what might be wrong?

From checking the code I can see that this is printed if the system version is less than 3.5 or there was an error when importing asyncio. However, everything is installed from scratch and this is still happening.

**Comment by ashishb** [comment]
This is the code which checks - https://github.com/ashishb/adb-enhanced/blob/3f235b7e62a52dc2b98117b25e1ed47615a2b17e/src/main.py#L373
So, it seems like somehow you are still using Python2 version while running `adbe`.

**Comment by lordcodes** [comment]
I removed it and installed with:

`python3 -m pip install adb-enhanced`

Logging from adbe includes "python/3.7.6_1/Frameworks/Python.framework" so I am pretty sure python 3 is being used.

Ah well, will just leave it for now. I still seem to be able to use adbe so will just come back to it if there are any problems in the future.

**Comment by ashishb** [comment]
@lordcodes Can you help me debug this by logging in adb-enhanced/src/main.py and seeing what does `_using_python2()` return?

**Comment by lordcodes** [comment]
@ashishb Sure thing 👍

**Comment by lordcodes** [comment]
Ahhh I just realised.

It doesn't print the warning about python 2 deprecation when I run adbe, so I don't think that is the issue.

It prints: "Use python3 for faster execution of this call" when I use:

`adbe apps list debug`

That seems to use a different check

**Comment by ashishb** [comment]
I will fix the message but do you have async IO installed or not?

**Comment by lordcodes** [comment]
I have the asyncio package installed.
Will investigate with some logging what is preventing the 'import asyncio_helper' from working.

**Comment by ashishb** [comment]
Relevant code:
https://github.com/ashishb/adb-enhanced/blob/3f235b7e62a52dc2b98117b25e1ed47615a2b17e/src/adb_enhanced.py#L23-L32

Ashish

**Comment by ashishb** [comment]
Hi @lordcodes 
Are you still facing this issue?

**Comment by ashishb** [comment]
I fixed the message in b3e1a70fdfea7013873cb1b321e3a294ba655806

**Comment by lordcodes** [comment]
Yeah i just had to ignore it, couldn’t find what was causing it. Maybe I have just messed up my python environment.

We can close and I will reopen if I find an actual bug that needs fixing 👍
